title: Austin Lee IT"'"s blog
author: Austin Lee
email: AustinLeeIT@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first site using github pages! Please check back often for updates and new projects.
#Write an awesome description for your new site here. You can edit this
#line in _config.yml. It will appear in your document head meta (for
#Google search results) and in your feed.xml site description.

# social links
twitter_username: AustinLeeIT # DO NOT include the @ character, or else the build will fail!
github_username:  AustinLeeIT # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: slate
